apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
  - protocol: TCP
    port: 8081       # Puerto que exponemos externamente
    targetPort: 8080 # Puerto en los pods
  type: NodePort
