apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  selector:
    app: producer
  ports:
  - protocol: TCP
    port: 8080       # Puerto que exponemos externamente
    targetPort: 8080 # Puerto en los pods
  type: NodePort
