spring:
  application:
    name: producer
  profiles:
    active: prod
  config:
    #import: optional:configserver:http://configuration-server-service:8080
    import: optional:configserver:${CONFIGURATION_SERVER_ADDRESS}
