apiVersion: v1
kind: PersistentVolume
metadata:
  name: configuration-pv
spec:
  storageClassName: configurations-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/docker/configurations
    type: Directory

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configuration-pvc
spec:
  storageClassName: configurations-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  volumeName: configuration-pv


