apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-container
        image: redis:alpine
        ports:
        - containerPort: 6379
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - redis-cli -h 127.0.0.1 ping | grep PONG
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - redis-cli -h 127.0.0.1 ping | grep PONG
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis-app
  ports:
  - protocol: TCP
    port: 6379       # Puerto expuesto en el servicio
    targetPort: 6379 # Puerto dentro del pod


