apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-app
  template:
    metadata:
      labels:
        app: consul-app
    spec:
      containers:
      - name: consul-container
        image: consul:1.15
        command: 
        - "consul"
        args:
        - "agent"
        - "-server"
        - "-bootstrap"
        - "-client=0.0.0.0"
        - "-ui"
        - "-data-dir=/consul/data"
        - "-bind=0.0.0.0"
        - "-log-level=INFO"
        env:
        - name: CONSUL_BIND_INTERFACE
          value: "eth0"
        - name: CONSUL_CLIENT_INTERFACE
          value: "eth0"
        ports:
        - containerPort: 8500
        - containerPort: 8600
          protocol: UDP
        - containerPort: 8600
        livenessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /consul/config/consul.json
          subPath: consul.json
      securityContext:
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: configuration-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: consul-service
spec:
  type: ClusterIP
  selector:
    app: consul-app
  ports:
  - name: puerto-http
    protocol: TCP
    port: 8500
    targetPort: 8500
  - name: puerto-dns
    protocol: TCP
    port: 8600
    targetPort: 8600
  - name: puerto-udp
    protocol: UDP
    port: 8600
    targetPort: 8600

---

apiVersion: v1
kind: Service
metadata:
  name: consul-service-nodeport
spec:
  type: NodePort
  selector:
    app: consul-app
  ports:
  - name: ui
    port: 8500
    targetPort: 8500
    nodePort: 30001


