server:
  port: 8080

spring:
  application:
    name: consumer

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

producer:
  ### nombre del k8 service del productor y puerto externo del k8 service
  url: http://producer:8080
 
